name: Ping and Notify

on:
  schedule:
    - cron: "*/5 * * * *"   # รันทุก 5 นาที
  workflow_dispatch:         # สามารถกดรันเองได้

jobs:
  check-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve domain to IP
        id: dns
        run: |
          DOMAIN="${{ secrets.IP }}"
          IP=$(dig +short "$DOMAIN" | tail -n1)
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          echo "ip=$IP" >> $GITHUB_OUTPUT
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
          echo "domain=$DOMAIN" >> $GITHUB_OUTPUT

      - name: Send normal log
        run: |
          MESSAGE="ℹ️ Checked domain ${{ steps.dns.outputs.domain }}: IP = ${{ steps.dns.outputs.ip }} at ${{ steps.dns.outputs.timestamp }}"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MESSAGE"

      - name: Send alert if IP starts with 1.
        if: startsWith(steps.dns.outputs.ip, '1.')
        run: |
          ALERT="⚠️🚨 ALERT! Domain ${{ steps.dns.outputs.domain }} resolved to CRITICAL IP ${{ steps.dns.outputs.ip }} at ${{ steps.dns.outputs.timestamp }} 🚨⚠️"
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$ALERT"
