name: Ping and Notify

on:
  schedule:
    - cron: "*/5 * * * *"   # รันทุก 5 นาที
  workflow_dispatch:         # กดรันเองได้

jobs:
  check-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve domain to IP
        id: dns
        run: |
          DOMAIN="${{ secrets.IP }}"
          IP=$(dig +short "$DOMAIN" | tail -n1)
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          echo "ip=$IP" >> $GITHUB_OUTPUT
          echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT
          echo "domain=$DOMAIN" >> $GITHUB_OUTPUT

      - name: Send Telegram message
        run: |
          if [[ "${{ steps.dns.outputs.ip }}" == 1.* ]]; then
            MESSAGE="⚠️🚨 ALERT! Domain ${{ steps.dns.outputs.domain }} resolved to CRITICAL IP ${{ steps.dns.outputs.ip }} at ${{ steps.dns.outputs.timestamp }} 🚨⚠️"
          else
            MESSAGE="✅ Domain ${{ steps.dns.outputs.domain }} resolved to IP ${{ steps.dns.outputs.ip }} at ${{ steps.dns.outputs.timestamp }}"
          fi

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MESSAGE"
