name: Ping and Notify

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  check-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Resolve domain to IP silently
        id: dns
        run: |
          DOMAIN="${{ secrets.IP }}"
          IP=$(dig +short "$DOMAIN" | tail -n1)
          # ใช้เวลา Bangkok (UTC+7)
          TIMESTAMP=$(TZ="Asia/Bangkok" date +"%Y-%m-%d %H:%M:%S")
          # เก็บ env เงียบ ๆ
          echo "DOMAIN=$DOMAIN" >> $GITHUB_ENV
          echo "IP=$IP" >> $GITHUB_ENV
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      - name: Send Telegram message
        run: |
          if [[ "$IP" == 1.* ]]; then
            MESSAGE="⚠️🚨 ALERT! Domain $DOMAIN resolved to CRITICAL IP $IP at $TIMESTAMP (Bangkok) 🚨⚠️"
          else
            MESSAGE="✅ Domain $DOMAIN checked at $IP at $TIMESTAMP"
          fi

          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$MESSAGE"
